[project]
name = "digest-lm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "openai>=1.82.1",
    "python-dotenv>=1.1.0",
]
